/**
 * Compile-time reconciliation of the two Env shapes (Phase 1e task 3).
 *
 * `Env` (global) is generated by `wrangler types` from the bindings declared in
 * `wrangler.jsonc` (DB, OAUTH_KV, BODIES — the locally-emulable set). `BrainBindings` is the
 * frozen hand-written interface in `packages/db/src/env.ts`, the authoritative superset that
 * also names the deploy-only / faked-in-tests bindings (CHUNK_INDEX, ENTITY_INDEX, AI) and
 * the string vars (AI_GATEWAY_ID, CLERK_FRONTEND_API, DEVICE_FLOW_SECRET).
 *
 * This function typechecks ONLY if every wrangler-generated binding is present in
 * `BrainBindings` with a compatible type — i.e. the generated `Env` ⊆ `BrainBindings`. It is
 * never called; it exists so `tsc` fails the `check` gate the moment the two drift.
 */
import type { BrainBindings } from "@brain/db"

export const assertEnvReconciled = (bindings: BrainBindings): Env => bindings
