/// <reference types="@cloudflare/vitest-pool-workers/types" />

/**
 * Test-only typing. `cloudflare:test`'s `env` is typed as `Cloudflare.Env` — the namespace
 * generated by `wrangler types` (DB, OAUTH_KV, BODIES from `wrangler.jsonc`). We augment it
 * with `MIGRATIONS`, the pre-split migration SQL injected as a miniflare binding by
 * `vitest.config.ts` (not a deployed binding, so it lives only in this test-scoped d.ts).
 */
declare namespace Cloudflare {
  interface Env {
    MIGRATIONS: string[]
  }
}
