/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/brain
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BrainPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/client.ts
var import_obsidian = require("obsidian");
var BrainClient = class {
  constructor(baseUrl, apiKey) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.authHeader = `Bearer ${apiKey}`;
  }
  get headers() {
    return {
      Authorization: this.authHeader,
      "Content-Type": "application/json"
    };
  }
  // ── REST endpoints ──────────────────────────────────────────────────────────
  /** POST /think — hybrid search + cited synthesis. */
  async think(input) {
    return this.postRest("/think", input);
  }
  /** POST /search — cheap hybrid search. */
  async search(input) {
    return this.postRest("/search", input);
  }
  /** POST /graph/backlinks — pages that link to the given slug. */
  async getBacklinks(input) {
    return this.postRest("/graph/backlinks", input);
  }
  // ── tRPC endpoints (no direct REST route) ───────────────────────────────────
  /**
   * tRPC mutation: POST /trpc/memory_set?batch=1
   * Request body: {"0": <MemorySetInput>}
   * Response: [{result:{data:<MemorySetOutput>}}]
   */
  async memorySet(input) {
    return this.trpcMutation("memory_set", input);
  }
  /**
   * tRPC query: GET /trpc/okf_export?batch=1&input=URIEncoded({"0":<OkfExportInput>})
   * Response: [{result:{data:<OkfExportOutput>}}]
   */
  async okfExport(input = {}) {
    return this.trpcQuery("okf_export", input);
  }
  // ── Private helpers ─────────────────────────────────────────────────────────
  async postRest(path, body) {
    const resp = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}${path}`,
      method: "POST",
      headers: this.headers,
      body: JSON.stringify(body),
      throw: false
    });
    if (resp.status >= 400) {
      throw new Error(`Brain API ${path} (${resp.status.toString()}): ${resp.text}`);
    }
    return resp.json;
  }
  async trpcMutation(procedure, input) {
    const resp = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/trpc/${procedure}?batch=1`,
      method: "POST",
      headers: this.headers,
      body: JSON.stringify({ "0": input }),
      throw: false
    });
    if (resp.status >= 400) {
      throw new Error(`Brain tRPC ${procedure} (${resp.status.toString()}): ${resp.text}`);
    }
    const batch = resp.json;
    return batch[0].result.data;
  }
  async trpcQuery(procedure, input) {
    const encodedInput = encodeURIComponent(JSON.stringify({ "0": input }));
    const resp = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/trpc/${procedure}?batch=1&input=${encodedInput}`,
      method: "GET",
      // GET: no Content-Type (no body).
      headers: { Authorization: this.authHeader },
      throw: false
    });
    if (resp.status >= 400) {
      throw new Error(`Brain tRPC ${procedure} (${resp.status.toString()}): ${resp.text}`);
    }
    const batch = resp.json;
    return batch[0].result.data;
  }
};

// src/modals.ts
var import_obsidian2 = require("obsidian");
var SearchModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this._searchTimer = null;
    this._latestQuery = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Search Brain" });
    const resultsEl = contentEl.createDiv({ cls: "brain-search-results" });
    new import_obsidian2.Setting(contentEl).setName("Query").addText((text) => {
      text.setPlaceholder("Search the Brain\u2026").onChange((value) => {
        if (this._searchTimer !== null) {
          window.clearTimeout(this._searchTimer);
          this._searchTimer = null;
        }
        if (value.length >= 3) {
          this._searchTimer = window.setTimeout(() => {
            this._latestQuery = value;
            void this.runSearch(value, resultsEl);
          }, 200);
        } else {
          this._latestQuery = "";
          resultsEl.empty();
        }
      });
      window.setTimeout(() => text.inputEl.focus(), 10);
    });
  }
  async runSearch(query, container) {
    container.empty();
    container.createEl("p", { text: "Searching\u2026", cls: "brain-status" });
    try {
      const result = await this.plugin.getClient().search({ query, topK: 10 });
      if (query !== this._latestQuery) return;
      container.empty();
      if (result.hits.length === 0) {
        container.createEl("p", { text: "No results.", cls: "brain-status" });
        return;
      }
      for (const hit of result.hits) {
        this.renderHit(hit, container);
      }
    } catch (err) {
      if (query !== this._latestQuery) return;
      container.empty();
      container.createEl("p", {
        text: `Error: ${String(err)}`,
        cls: "brain-status brain-error"
      });
    }
  }
  renderHit(hit, container) {
    const item = container.createDiv({ cls: "brain-search-item" });
    item.createEl("strong", { text: hit.slug });
    item.createEl("p", { text: hit.snippet, cls: "brain-snippet" });
    item.addEventListener("click", () => {
      void this.app.workspace.openLinkText(hit.slug, "/", false);
      this.close();
    });
  }
  onClose() {
    if (this._searchTimer !== null) {
      window.clearTimeout(this._searchTimer);
      this._searchTimer = null;
    }
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiBaseUrl: "https://brain-api.dominik-fretz.workers.dev",
  apiKey: "",
  defaultScope: "",
  brainFolder: "Brain"
};
var BrainSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Brain settings" });
    new import_obsidian3.Setting(containerEl).setName("API base URL").setDesc("URL of your deployed Brain API worker.").addText((text) => {
      text.setPlaceholder("https://brain-api.example.workers.dev").setValue(this.plugin.settings.apiBaseUrl).onChange(async (value) => {
        this.plugin.settings.apiBaseUrl = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("API key").setDesc(
      "Your bk_ API key. Stored in plain text inside Obsidian's plugin data.json \u2014 see README for security notes."
    ).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("bk_\u2026").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Default scope").setDesc(
      "Optional scope pre-filter applied to every think/search query. Leave blank to search across all your content."
    ).addText((text) => {
      text.setPlaceholder("my-project").setValue(this.plugin.settings.defaultScope).onChange(async (value) => {
        this.plugin.settings.defaultScope = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Brain folder").setDesc("Vault folder where Pull Brain Notes writes files (created if absent).").addText((text) => {
      text.setPlaceholder("Brain").setValue(this.plugin.settings.brainFolder).onChange(async (value) => {
        this.plugin.settings.brainFolder = value.trim() || "Brain";
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/main.ts
var BrainPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.client = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BrainSettingTab(this.app, this));
    this.addCommand({
      id: "brain-think",
      name: "Ask the Brain",
      editorCallback: (editor, view) => {
        var _a, _b;
        const selection = editor.getSelection().trim();
        const query = selection.length > 0 ? selection : (_b = (_a = view.file) == null ? void 0 : _a.basename) != null ? _b : "";
        if (query.length === 0) {
          new import_obsidian4.Notice("Brain: open a note or select text to ask a question.");
          return;
        }
        void this.runThink(query, editor);
      }
    });
    this.addCommand({
      id: "brain-search",
      name: "Search Brain",
      callback: () => {
        new SearchModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "brain-backlinks",
      name: "Show Brain backlinks for active note",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file === null) return false;
        if (!checking) void this.runBacklinks(file);
        return true;
      }
    });
    this.addCommand({
      id: "brain-capture",
      name: "Capture active note to Brain memory",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file === null) return false;
        if (!checking) void this.runCapture(file);
        return true;
      }
    });
    this.addCommand({
      id: "brain-pull",
      name: "Pull Brain notes into vault",
      callback: () => {
        void this.runPull();
      }
    });
    this.addRibbonIcon("brain", "Brain", () => {
      new SearchModal(this.app, this).open();
    });
  }
  onunload() {
  }
  // ── Settings ────────────────────────────────────────────────────────────────
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
    this.refreshClient();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshClient();
  }
  /** Rebuild the client whenever the URL or key changes. */
  refreshClient() {
    const { apiBaseUrl, apiKey } = this.settings;
    if (apiBaseUrl.length > 0 && apiKey.length > 0) {
      this.client = new BrainClient(apiBaseUrl, apiKey);
    } else {
      this.client = null;
    }
  }
  /**
   * Return the active client, or throw a user-friendly error if not configured.
   * Commands call this rather than accessing `this.client` directly.
   */
  getClient() {
    if (this.client === null) {
      throw new Error(
        "Brain plugin not configured. Open Settings \u2192 Brain and enter your API URL and key."
      );
    }
    return this.client;
  }
  // ── Command implementations ─────────────────────────────────────────────────
  async runThink(query, editor) {
    const notice = new import_obsidian4.Notice("Brain: thinking\u2026", 0);
    try {
      const client = this.getClient();
      const input = {
        query,
        ...this.settings.defaultScope.length > 0 ? { scope: this.settings.defaultScope } : {}
      };
      const result = await client.think(input);
      notice.hide();
      editor.replaceRange(formatThinkResult(result), editor.getCursor("to"));
    } catch (err) {
      notice.hide();
      new import_obsidian4.Notice(`Brain: ${String(err)}`);
    }
  }
  async runBacklinks(file) {
    const slug = file.path.replace(/\.md$/, "");
    const notice = new import_obsidian4.Notice("Brain: fetching backlinks\u2026", 0);
    try {
      const client = this.getClient();
      const result = await client.getBacklinks({ target: slug });
      notice.hide();
      if (result.links.length === 0) {
        new import_obsidian4.Notice(`Brain: no backlinks found for "${slug}".`);
        return;
      }
      const lines = [
        `# Brain backlinks \u2014 ${file.basename}`,
        "",
        `Slug: \`${slug}\``,
        "",
        ...result.links.map(
          (l) => `- **${l.fromId}** \u2192 (${l.linkType})${l.context.length > 0 ? `: _${l.context}_` : ""}`
        ),
        ""
      ];
      const safeName = file.path.replace(/\.md$/, "").replace(/\//g, " \xBB ");
      const destPath = `${this.settings.brainFolder}/Backlinks \u2014 ${safeName}.md`;
      await this.writeVaultFile(destPath, lines.join("\n"));
      await this.app.workspace.openLinkText(destPath, "/", false);
    } catch (err) {
      notice.hide();
      new import_obsidian4.Notice(`Brain: ${String(err)}`);
    }
  }
  async runCapture(file) {
    var _a, _b;
    const notice = new import_obsidian4.Notice("Brain: capturing note\u2026", 0);
    try {
      const client = this.getClient();
      const content = await this.app.vault.read(file);
      const slug = file.path.replace(/\.md$/, "");
      const cache = this.app.metadataCache.getFileCache(file);
      const type = (_b = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.brain_type) != null ? _b : "note";
      const input = {
        slug,
        type,
        body: content,
        title: file.basename,
        ...this.settings.defaultScope.length > 0 ? { scope: this.settings.defaultScope } : {}
      };
      const result = await client.memorySet(input);
      notice.hide();
      new import_obsidian4.Notice(
        `Brain: captured "${result.slug}" (v${result.version.toString()}${result.changed ? ", updated" : ", unchanged"}).`
      );
    } catch (err) {
      notice.hide();
      new import_obsidian4.Notice(`Brain: ${String(err)}`);
    }
  }
  async runPull() {
    const notice = new import_obsidian4.Notice("Brain: pulling notes\u2026", 0);
    try {
      const client = this.getClient();
      const result = await client.okfExport({});
      notice.hide();
      if (result.files.length === 0) {
        new import_obsidian4.Notice("Brain: no notes to pull.");
        return;
      }
      await this.writeOkfBundle(result.files);
      new import_obsidian4.Notice(
        `Brain: pulled ${result.files.length.toString()} notes into "${this.settings.brainFolder}".`
      );
    } catch (err) {
      notice.hide();
      new import_obsidian4.Notice(`Brain: ${String(err)}`);
    }
  }
  // ── Vault helpers ───────────────────────────────────────────────────────────
  /**
   * Write an OKF bundle into the vault under the configured Brain folder.
   * Each file's `path` is relative; we prefix it with `brainFolder/`.
   */
  async writeOkfBundle(files) {
    await this.ensureFolder(this.settings.brainFolder);
    for (const file of files) {
      const safePath = this.sanitizeRelPath(file.path);
      if (safePath.length === 0) continue;
      const targetPath = `${this.settings.brainFolder}/${safePath}`;
      await this.writeVaultFile(targetPath, file.content);
    }
  }
  /**
   * Strip leading slashes and remove `.` / `..` segments from a server-supplied
   * relative path so it cannot escape the Brain folder.
   */
  sanitizeRelPath(rawPath) {
    return rawPath.replace(/^\/+/, "").split("/").filter((seg) => seg.length > 0 && seg !== "." && seg !== "..").join("/");
  }
  /**
   * Create or overwrite a vault file, ensuring its parent folder exists.
   * Uses Vault API only — no fs, path, or Buffer.
   */
  async writeVaultFile(targetPath, content) {
    const lastSlash = targetPath.lastIndexOf("/");
    if (lastSlash > 0) {
      await this.ensureFolder(targetPath.slice(0, lastSlash));
    }
    const existing = this.app.vault.getAbstractFileByPath(targetPath);
    if (existing instanceof import_obsidian4.TFile) {
      await this.app.vault.modify(existing, content);
    } else if (existing === null) {
      await this.app.vault.create(targetPath, content);
    } else if (existing instanceof import_obsidian4.TFolder) {
      new import_obsidian4.Notice(`Brain: cannot write "${targetPath}" \u2014 a folder already exists at that path.`);
    }
  }
  /** Create a vault folder if it does not already exist. */
  async ensureFolder(folderPath) {
    const existing = this.app.vault.getAbstractFileByPath(folderPath);
    if (existing === null) {
      await this.app.vault.createFolder(folderPath);
    }
  }
};
function formatThinkResult(result) {
  const lines = ["", "> [!brain] Brain", `> ${result.answer.replace(/\n/g, "\n> ")}`];
  if (result.citations.length > 0) {
    lines.push("> ");
    lines.push(`> **Sources:** ${result.citations.map((c) => `[[${c.slug}]]`).join(", ")}`);
  }
  if (result.gaps.length > 0) {
    lines.push("> ");
    lines.push(`> **Gaps:** ${result.gaps.join("; ")}`);
  }
  if (result.warnings.length > 0) {
    lines.push("> ");
    lines.push(`> **Warnings:** ${result.warnings.join("; ")}`);
  }
  lines.push("");
  return lines.join("\n");
}
