/**
 * `@brain/db/admin` (PRD §7.1/§9.2.2) — the admin op contracts + bound handlers: `mint_api_key`,
 * `get_token_spend`, `memberships`, `create_org`, `list_orgs`, and dashboard list/stats ops.
 * Registered into the shared op-registry like every other op family so the MCP/tRPC/CLI catalog
 * cannot drift; the handlers fail CLOSED on a non-admin caller where required.
 */
export type {
  AdminBoundOp,
  AdminOpContext,
  CreateOrgInput,
  GetStatsOutput,
  ListAuditEntry,
  ListBackfillRunRow,
  ListDocumentsRow,
  ListSessionRow,
  MembershipOpRow,
  MintApiKeyOpInput,
  OrgListRow,
  TokenSpendOpOutput,
} from "./ops"
export {
  ADMIN_OPS,
  CREATE_ORG_OP,
  createOrgCore,
  createOrgOp,
  GET_STATS_OP,
  GET_TOKEN_SPEND_OP,
  getStatsCore,
  getStatsOp,
  getTokenSpendCore,
  getTokenSpendOp,
  LIST_AUDIT_OP,
  LIST_BACKFILL_RUNS_OP,
  LIST_DOCUMENTS_OP,
  LIST_ORGS_OP,
  LIST_SESSIONS_OP,
  listAuditCore,
  listAuditOp,
  listBackfillRunsCore,
  listBackfillRunsOp,
  listDocumentsCore,
  listDocumentsOp,
  listOrgsCore,
  listOrgsOp,
  listSessionsCore,
  listSessionsOp,
  MEMBERSHIPS_OP,
  MINT_API_KEY_OP,
  membershipsCore,
  membershipsOp,
  mintApiKeyCore,
  mintApiKeyOp,
  registerAdminOps,
} from "./ops"
